import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import FarcasterSessionWrapper from '@/providers/FarcasterSessionWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: any;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className} suppressHydrationWarning={true}>
        <FarcasterSessionWrapper session={session}>
          {children}
        </FarcasterSessionWrapper>
      </body>
    </html>
  );
}
