import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import PrivyWrapper from '@/providers/PrivyProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <PrivyWrapper>
        <body className={inter.className}>{children}</body>
      </PrivyWrapper>
    </html>
  );
}
